#ifndef EXTINT_CONFIG_H
#define EXTINT_CONFIG_H

/* Can be:  RISING_EDGE
 * 			FALLING_EDGE
 * 			LOW_LEVEL
 * 			LOGICAL_CHANGE
 */

//#define SENSE_CONTROL_EXT0 LOGICAL_CHANGE
//#define SENSE_CONTROL_EXT1 FALLING_EDGE
//#define SENSE_CONTROL_EXT2 FALLING_EDGE

#endif
